using JasperFx.CodeGeneration;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Shared.Domain;
using Shared.Modules;
using Shared.Persistence;
using Wolverine;
#if (UseAzureServiceBus)
using Wolverine.AzureServiceBus;
#endif
using Wolverine.EntityFrameworkCore;
using Wolverine.FluentValidation;
using Wolverine.Persistence;
#if (UsePostgreSQL)
using Wolverine.Postgresql;
#endif
#if (UseRabbitMq)
using Wolverine.RabbitMQ;
#endif
#if (UseSqlServer)
using Wolverine.SqlServer;
#endif

namespace Shared.Messaging;

public static class MessagingExtensions
{
    /// <summary>
    /// Configures Wolverine as mediator and message bus for all modules:
    /// durable local queues, a transactional outbox/inbox in the shared database, EF Core transactions,
    /// domain events published after commit and FluentValidation middleware.
    /// </summary>
    public static IHostApplicationBuilder UseModularWolverine(
        this IHostApplicationBuilder builder,
        IReadOnlyCollection<IModule> modules)
    {
        builder.UseWolverine(options =>
        {
            var connectionString = builder.Configuration.GetConnectionString(DatabaseDefaults.ConnectionStringName)
                ?? throw new InvalidOperationException(
                    $"Connection string '{DatabaseDefaults.ConnectionStringName}' is not configured.");

#if (UsePostgreSQL)
            options.PersistMessagesWithPostgresql(connectionString, DatabaseDefaults.MessagingSchema);
#else
            options.PersistMessagesWithSqlServer(connectionString, DatabaseDefaults.MessagingSchema);
#endif
            options.Durability.MessageStorageSchemaName = DatabaseDefaults.MessagingSchema;
            options.Durability.MessageIdentity = MessageIdentity.IdAndDestination;

            // Command handlers call no SaveChangesAsync: Wolverine opens a transaction per message and commits the
            // DbContext, the scraped domain events and the outbox together. Query handlers opt out with [NonTransactional].
            options.UseEntityFrameworkCoreTransactions(TransactionMiddlewareMode.Eager);
            options.Policies.AutoApplyTransactions();
            options.Policies.UseDurableLocalQueues();

            // Domain events raised by aggregates are published through the outbox once the transaction commits.
            options.PublishDomainEventsFromEntityFrameworkCore<IAggregateRoot, IDomainEvent>(
                aggregate => aggregate.DomainEvents);

            // Every handler of the same message runs independently (own transaction, own retries).
            options.MultipleHandlerBehavior = MultipleHandlerBehavior.Separated;

            options.UseFluentValidation();

            if (builder.Environment.IsProduction())
            {
                // Use the handler code pre-generated by `dotnet run -- codegen write` (see the Dockerfile);
                // anything missing is generated at startup.
                options.CodeGeneration.TypeLoadMode = TypeLoadMode.Auto;
            }
#if (UseBroker)

            ConfigureBroker(builder, options);
#endif

            foreach (var module in modules)
            {
                options.Discovery.IncludeAssembly(module.Assembly);
                module.ConfigureMessaging(options);
            }
        });

        return builder;
    }
#if (UseBroker)

    /// <summary>
    /// Integration events travel over the broker, so modules could later run as separate services.
    /// Domain events and commands stay in-process.
    /// </summary>
    private static void ConfigureBroker(IHostApplicationBuilder builder, WolverineOptions options)
    {
        var connectionString = builder.Configuration.GetConnectionString(MessagingDefaults.ConnectionStringName)
            ?? throw new InvalidOperationException(
                $"Connection string '{MessagingDefaults.ConnectionStringName}' is not configured.");

        options.Policies.DisableConventionalLocalRouting();
        options.Publish(rule =>
        {
            rule.MessagesImplementing<IDomainEvent>();
            rule.ToLocalQueue("domain-events");
        });

        options.Policies.UseDurableOutboxOnAllSendingEndpoints();
        options.Policies.UseDurableInboxOnAllListeners();
#if (UseRabbitMq)

        options.UseRabbitMq(new Uri(connectionString))
            .AutoProvision()
            .UseConventionalRouting(convention => convention.IncludeTypes(MessagingDefaults.IsIntegrationEvent));
#elif (UseAzureServiceBus)

        var managementConnectionString = builder.Configuration["Messaging:ManagementConnectionString"];
        var transport = string.IsNullOrEmpty(managementConnectionString)
            ? options.UseAzureServiceBus(connectionString)
            : options.UseAzureServiceBusEmulator(connectionString, managementConnectionString);

        transport
            .AutoProvision()
            .UseConventionalRouting(convention => convention.IncludeTypes(MessagingDefaults.IsIntegrationEvent));
#endif
    }
#endif
}
